"""Shared deterministic codegen helpers. No timestamps, stable ordering."""
from __future__ import annotations

from utag_core.ir import Constraint, FieldSpec, ScalarKind

HEADER = "# generated by utag 2.0.0 — deterministic; do not edit by hand\n"

PY_TYPES = {
    ScalarKind.string: "str", ScalarKind.integer: "int", ScalarKind.number: "float",
    ScalarKind.boolean: "bool", ScalarKind.datetime: "datetime", ScalarKind.any: "Any",
}
ZOD_TYPES = {
    ScalarKind.string: "z.string()", ScalarKind.integer: "z.number().int()",
    ScalarKind.number: "z.number()", ScalarKind.boolean: "z.boolean()",
    ScalarKind.datetime: "z.iso.datetime()", ScalarKind.any: "z.unknown()",
}


def snake(name: str) -> str:
    return name.replace("-", "_")


def py_field_type(f: FieldSpec) -> str:
    base = PY_TYPES[f.type] if isinstance(f.type, ScalarKind) else str(f.type)
    if f.array:
        base = f"list[{base}]"
    if f.nullable:
        base = f"{base} | None"
    return base


def py_constraints(cs: list[Constraint]) -> str:
    """map portable constraints -> pydantic Field kwargs"""
    m = {"min_length": "min_length", "max_length": "max_length",
         "ge": "ge", "le": "le", "pattern": "pattern"}
    parts = [f"{m[c.kind]}={c.value!r}" for c in cs if c.kind in m]
    return ", ".join(parts)


def zod_chain(f: FieldSpec) -> str:
    if isinstance(f.type, ScalarKind):
        expr = ZOD_TYPES[f.type]
        for c in f.constraints:
            if c.kind == "min_length": expr += f".min({c.value})"
            elif c.kind == "max_length": expr += f".max({c.value})"
            elif c.kind == "ge": expr += f".gte({c.value})"
            elif c.kind == "le": expr += f".lte({c.value})"
            elif c.kind == "pattern": expr += f".regex(/{c.value}/)"
            elif c.kind == "format" and c.value == "email": expr = "z.email()"
    else:
        expr = f"{f.type}Schema"
    if f.array:
        expr = f"z.array({expr})"
    if f.nullable:
        expr += ".nullable()"
    if not f.required:
        expr += ".optional()"
    return expr
