"""Meta-generation: generators that generate generators (the moat).

A GeneratorSpec (itself a strict Pydantic model, producible by any StructuredPort
via the repair loop) is compiled into a new, immediately-registrable generator
module + its unit test. The emitted module uses only public utag_core APIs, so
meta-generated generators are indistinguishable from hand-written ones
(DoD dod-arch-003: extension without touching core).
"""
from __future__ import annotations

from pydantic import BaseModel, ConfigDict, Field, field_validator

from utag_core.ir import ModuleSpec
from utag_core.registry import register_generator
from utag_generators._codegen import snake


class OutputRule(BaseModel):
    model_config = ConfigDict(extra="forbid")
    filename_template: str = Field(description="e.g. '{module}.txt'")
    line_template: str = Field(description="per-type line, fields: {type_name}, {field_names}")
    header: str = ""


class GeneratorSpec(BaseModel):
    """What an LLM (or human) must supply to mint a new generator."""
    model_config = ConfigDict(extra="forbid")
    target: str = Field(pattern=r"^[a-z0-9]+(-[a-z0-9]+)*$", description="registry key")
    class_name: str = Field(pattern=r"^[A-Z][A-Za-z0-9]*Generator$")
    doc: str = Field(min_length=10, max_length=500)
    output: OutputRule
    validator_kind: str = "yaml"

    @field_validator("target")
    @classmethod
    def _no_core_collisions(cls, v: str) -> str:
        reserved = {"pydantic-models", "zod-schemas", "agent-skill",
                    "prompt-yaml", "openapi-3.1", "design-md", "generator"}
        if v in reserved:
            raise ValueError(f"target {v!r} collides with a built-in generator")
        return v


MODULE_TEMPLATE = '''"""{doc}

meta-generated by utag 2.0.0 from a validated GeneratorSpec. Deterministic.
"""
from __future__ import annotations

from utag_core.ir import ModuleSpec
from utag_core.registry import register_generator


@register_generator({target!r})
class {class_name}:
    def generate(self, module: ModuleSpec) -> dict[str, str]:
        lines = [{header!r}] if {header!r} else []
        for t in module.types:
            lines.append({line_template!r}.format(
                type_name=t.name, field_names=", ".join(f.name for f in t.fields)))
        content = "\\n".join(lines).rstrip() + "\\n"
        return {{{filename_template!r}.format(module=module.name): content}}
'''

TEST_TEMPLATE = '''"""meta-generated test for {target}."""
from utag_core.ir import FieldSpec, ModuleSpec, TypeSpec

import {module_name}  # noqa: F401  registers the generator
from utag_core.registry import get_generator


def test_{fn}_generates_deterministically():
    m = ModuleSpec(name="sample", types=[TypeSpec(name="Thing", fields=[
        FieldSpec(name="id", type="string")])])
    g = get_generator({target!r})
    a, b = g.generate(m), g.generate(m)
    assert a == b and a, "must be deterministic and non-empty"
'''


@register_generator("generator")
class GeneratorGenerator:
    """Target 'generator': emits a new generator package from module.provenance['spec_json']."""

    def generate(self, module: ModuleSpec) -> dict[str, str]:
        spec = GeneratorSpec.model_validate_json(module.provenance["spec_json"])
        return emit_generator(spec)


def emit_generator(spec: GeneratorSpec) -> dict[str, str]:
    module_name = f"utag_gen_{snake(spec.target)}"
    src = MODULE_TEMPLATE.format(
        doc=spec.doc, target=spec.target, class_name=spec.class_name,
        header=spec.output.header, line_template=spec.output.line_template,
        filename_template=spec.output.filename_template,
    )
    test = TEST_TEMPLATE.format(target=spec.target, module_name=module_name,
                                fn=snake(spec.target))
    return {f"{module_name}.py": src, f"test_{module_name}.py": test}
