from __future__ import annotations
from utag_core.ir import ModuleSpec
from utag_core.registry import register_generator

@register_generator("arazzo-workflows")
class ArazzoWorkflowsGenerator:
    def generate(self, module: ModuleSpec) -> dict[str, str]:
        import yaml
        
        steps = []
        for idx, op in enumerate(module.operations):
            step = {
                "stepId": f"step-{op.name}",
                "description": op.description or f"Execute {op.name}",
                "operationId": op.name,
            }
            if op.responses:
                # Expect the first response status code
                status = op.responses[0].status_code
                step["successCriteria"] = [
                    {"condition": f"$statusCode == {status}"}
                ]
            steps.append(step)
            
        arazzo_doc = {
            "arazzo": "1.0.0",
            "info": {
                "title": f"{module.name} Workflows",
                "summary": module.description or "Auto-generated Arazzo workflows",
                "version": "1.0.0"
            },
            "sourceDescriptions": [
                {
                    "name": f"{module.name}-api",
                    "url": f"{module.name}.openapi.json",
                    "type": "openapi"
                }
            ],
            "workflows": [
                {
                    "workflowId": f"{module.name}-main-workflow",
                    "summary": "Generated default workflow executing all operations sequentially",
                    "steps": steps
                }
            ] if steps else []
        }
        
        return {f"{module.name}-workflows.arazzo.yaml": yaml.safe_dump(arazzo_doc, sort_keys=False)}

@register_generator("arazzo-agent-workflows")
class ArazzoAgentWorkflowsGenerator:
    def generate(self, module: ModuleSpec) -> dict[str, str]:
        import yaml
        # Define agent-specific workflow steps based on operations
        steps = [
            {
                "stepId": f"agent-{op.name}",
                "description": f"Agent-driven execution of {op.name}",
                "operationId": op.name,
                "parameters": {op.path: {"name": "context", "value": "$inputs.context"}}
            } for op in module.operations
        ]
        
        arazzo_doc = {
            "arazzo": "1.0.0",
            "info": {
                "title": f"{module.name} Agent Workflows",
                "version": "1.0.0"
            },
            "workflows": [
                {
                    "workflowId": f"{module.name}-agent-workflow",
                    "steps": steps
                }
            ]
        }
        return {f"{module.name}-agent-workflows.arazzo.yaml": yaml.safe_dump(arazzo_doc, sort_keys=False)}


@register_generator("arazzo-ui-model")
class ArazzoUiModelGenerator:
    def generate(self, module: ModuleSpec) -> dict[str, str]:
        import json
        nodes = []
        edges = []
        
        for idx, op in enumerate(module.operations):
            node_id = f"node_{idx}"
            nodes.append({
                "id": node_id,
                "label": op.name,
                "type": "operation"
            })
            if idx > 0:
                edges.append({
                    "source": f"node_{idx-1}",
                    "target": node_id
                })
                
        ui_model = {"nodes": nodes, "edges": edges}
        return {f"{module.name}-arazzo-ui.json": json.dumps(ui_model, indent=2) + "\n"}

@register_generator("overlay-patch")
class OverlayPatchGenerator:
    def generate(self, module: ModuleSpec) -> dict[str, str]:
        import yaml
        actions = []
        for op in module.operations:
            if not op.description:
                actions.append({
                    "target": f"$.paths['{op.path}'].{op.method.lower()}",
                    "update": {"description": f"Auto-generated description for {op.name}"}
                })
        
        overlay = {
            "overlay": "1.0.0",
            "info": {
                "title": f"Overlay for {module.name}",
                "version": "1.0.0"
            },
            "actions": actions
        }
        return {f"{module.name}-patch.yaml": yaml.safe_dump(overlay, sort_keys=False)}

@register_generator("overlay-diff")
class OverlayDiffGenerator:
    def generate(self, module: ModuleSpec) -> dict[str, str]:
        return {f"{module.name}-diff.yaml": "overlay: 1.0.0\n# diff patch stub\n"}


@register_generator("workflow-test-suite")
class WorkflowTestSuiteGenerator:
    def generate(self, module: ModuleSpec) -> dict[str, str]:
        lines = ["// generated by utag — workflow test suite", ""]
        for op in module.operations:
            lines.append(f"// Test workflow for {op.name}")
            lines.append(f"assert.ok(true); // Placeholder for actual workflow test logic")
        return {f"{module.name}-workflow-tests.ts": "\n".join(lines) + "\n"}
