"""IR -> single-binary Go agent-harness/control-plane.

Stack (real pins resolved via git ls-remote at authoring time):
  cobra v1.10.2, viper v1.21.0 (uses go-viper/mapstructure/v2 v2.5.0 internally).
Pattern: ONE Settings struct; viper reads defaults < config file < env (UTAG_*)
< flags and fills it via viper.Unmarshal (twelve-factor Factor III).
go:embed bakes UTAG-generated artifacts (openapi + prompt yaml from sibling
generators) into the binary — static, zero-dep control-plane.
"""
from __future__ import annotations

from utag_core.ir import ModuleSpec
from utag_core.registry import register_generator

COBRA_V, VIPER_V = "v1.10.2", "v1.21.0"

GO_MOD = """module utag-harness/{name}

go 1.22

require (
\tgithub.com/spf13/cobra {cobra}
\tgithub.com/spf13/viper {viper}
)
// mapstructure: viper >=1.19 depends on github.com/go-viper/mapstructure/v2 (transitive)
"""

MAIN_GO = """package main

import "utag-harness/{name}/cmd"

func main() {{
\tcmd.Execute()
}}
"""

CONFIG_GO = """// Package config: ONE struct describes all settings; viper fills it automatically.
package config

import "github.com/spf13/viper"

// Settings — single source of truth. Precedence (viper): explicit Set > flag >
// env (UTAG_*) > config file > default. Twelve-factor III: env-first config.
type Settings struct {
\tLogLevel    string `mapstructure:"log-level" json:"log-level"`
\tPort        int    `mapstructure:"port" json:"port"`
\tProvider    string `mapstructure:"provider" json:"provider"`
\tEndpoint    string `mapstructure:"endpoint" json:"endpoint"`
\tMaxAttempts int    `mapstructure:"max-attempts" json:"max-attempts"`
}

// Defaults registers every default in one place.
func Defaults(v *viper.Viper) {
\tv.SetDefault("log-level", "info")
\tv.SetDefault("port", 8080)
\tv.SetDefault("provider", "anthropic")
\tv.SetDefault("endpoint", "")
\tv.SetDefault("max-attempts", 3)
}

// Load = "read all my settings and fill this struct automatically."
func Load(v *viper.Viper) (Settings, error) {
\tvar s Settings
\terr := v.Unmarshal(&s) // decoding via go-viper/mapstructure/v2
\treturn s, err
}
"""

ROOT_GO = """package cmd

import (
\t"fmt"
\t"os"
\t"strings"

\t"github.com/spf13/cobra"
\t"github.com/spf13/viper"

\t"utag-harness/{name}/config"
)

var (
\tv        = viper.New()
\tsettings config.Settings
\tcfgFile  string
)

var rootCmd = &cobra.Command{{
\tUse:   "{kebab}",
\tShort: "{kebab} — utag-generated agent harness / control-plane",
\tLong:  "Single-binary control-plane generated by utag. Settings: one struct, filled by viper (defaults < config < env UTAG_* < flags).",
}}

func Execute() {{
\tif err := rootCmd.Execute(); err != nil {{
\t\tfmt.Fprintln(os.Stderr, err)
\t\tos.Exit(1)
\t}}
}}

func init() {{
\tcobra.OnInitialize(initConfig)
\trootCmd.PersistentFlags().StringVar(&cfgFile, "config", "", "config file (default ./utag.yaml)")
\trootCmd.PersistentFlags().String("log-level", "info", "log level")
\trootCmd.PersistentFlags().Int("port", 8080, "control-plane port")
\trootCmd.PersistentFlags().String("provider", "anthropic", "model provider")
\trootCmd.PersistentFlags().Int("max-attempts", 3, "bounded repair attempts")
\t_ = v.BindPFlags(rootCmd.PersistentFlags())
}}

func initConfig() {{
\tconfig.Defaults(v)
\tif cfgFile != "" {{
\t\tv.SetConfigFile(cfgFile)
\t}} else {{
\t\tv.SetConfigName("utag")
\t\tv.SetConfigType("yaml")
\t\tv.AddConfigPath(".")
\t}}
\tv.SetEnvPrefix("UTAG")
\tv.SetEnvKeyReplacer(strings.NewReplacer("-", "_", ".", "_"))
\tv.AutomaticEnv()
\t// twelve-factor: env overrides file; config file optional by design
\t_ = v.ReadInConfig()
\tvar err error
\tif settings, err = config.Load(v); err != nil {{
\t\tfmt.Fprintln(os.Stderr, "config:", err)
\t\tos.Exit(1)
\t}}
}}
"""

CONFIG_CMD_GO = """package cmd

import (
\t"encoding/json"
\t"fmt"

\t"github.com/spf13/cobra"
)

var configCmd = &cobra.Command{
\tUse:   "config",
\tShort: "Print fully-resolved settings as JSON (stdout, twelve-factor XI)",
\tRunE: func(cmd *cobra.Command, args []string) error {
\t\tb, err := json.MarshalIndent(settings, "", "  ")
\t\tif err != nil {
\t\t\treturn err
\t\t}
\t\tfmt.Println(string(b))
\t\treturn nil
\t},
}

func init() { rootCmd.AddCommand(configCmd) }
"""

ARTIFACTS_CMD_GO = """package cmd

import (
\t"fmt"
\t"io/fs"

\t"github.com/spf13/cobra"

\t"utag-harness/{name}/embedded"
)

var artifactsCmd = &cobra.Command{{
\tUse:   "artifacts [name]",
\tShort: "List or print utag artifacts baked into this binary (go:embed)",
\tArgs:  cobra.MaximumNArgs(1),
\tRunE: func(cmd *cobra.Command, args []string) error {{
\t\tif len(args) == 1 {{
\t\t\tb, err := embedded.FS.ReadFile("artifacts/" + args[0])
\t\t\tif err != nil {{
\t\t\t\treturn err
\t\t\t}}
\t\t\tfmt.Print(string(b))
\t\t\treturn nil
\t\t}}
\t\treturn fs.WalkDir(embedded.FS, "artifacts", func(p string, d fs.DirEntry, err error) error {{
\t\t\tif err == nil && !d.IsDir() {{
\t\t\t\tfmt.Println(p)
\t\t\t}}
\t\t\treturn err
\t\t}})
\t}},
}}

func init() {{ rootCmd.AddCommand(artifactsCmd) }}
"""

EMBED_GO = """// Package embedded bakes utag-generated artifacts into the binary (go:embed).
package embedded

import "embed"

//go:embed artifacts/*
var FS embed.FS
"""


@register_generator("go-harness")
class GoHarnessGenerator:
    def generate(self, module: ModuleSpec) -> dict[str, str]:
        # composition: embed sibling generators' deterministic artifacts
        from utag_core.registry import get_generator
        name = module.name
        kebab = name.replace("_", "-")
        embedded = {}
        for sibling in ("openapi-3.1", "prompt-yaml"):
            for rel, content in get_generator(sibling).generate(module).items():
                embedded[f"embedded/artifacts/{rel}"] = content
        files = {
            "go.mod": GO_MOD.format(name=name, cobra=COBRA_V, viper=VIPER_V),
            "main.go": MAIN_GO.format(name=name),
            "config/config.go": CONFIG_GO,
            "cmd/root.go": ROOT_GO.format(name=name, kebab=kebab),
            "cmd/config.go": CONFIG_CMD_GO,
            "cmd/artifacts.go": ARTIFACTS_CMD_GO.format(name=name),
            "embedded/embed.go": EMBED_GO,
        }
        files.update(embedded)
        return files
