from __future__ import annotations
import json
import yaml

from utag_core.ir import ModuleSpec
from utag_core.registry import register_generator

@register_generator("fastmcp-server")
class FastmcpServerGenerator:
    def generate(self, module: ModuleSpec) -> dict[str, str]:
        return {f"{module.name}-sdk-metadata.json": json.dumps({"target": "fastmcp-server", "implemented": False, "reason": "minimal stub"})}

@register_generator("typescript-mcp-server")
class TypescriptMcpServerGenerator:
    def generate(self, module: ModuleSpec) -> dict[str, str]:
        lines = ["// generated by utag — typescript mcp server", 'import { Server } from "@modelcontextprotocol/sdk/server/index.js";', ""]
        lines.append(f'const server = new Server({{ name: "{module.name}", version: "1.0.0" }}, {{}});')
        return {f"{module.name}-mcp.ts": "\n".join(lines)}

@register_generator("mcp-tool-manifest")
class McpToolManifestGenerator:
    def generate(self, module: ModuleSpec) -> dict[str, str]:
        tools = []
        for op in module.operations:
            input_schema = {
                "type": "object",
                "properties": {}
            }
            required = []
            
            # Path params
            for p in op.request.path_params:
                input_schema["properties"][p.name] = {"type": "string", "description": "Path parameter"}
                if p.required:
                    required.append(p.name)
                    
            # Query params
            for q in op.request.query_params:
                input_schema["properties"][q.name] = {"type": "string", "description": "Query parameter"}
                if q.required:
                    required.append(q.name)
                    
            if op.request.body_type:
                input_schema["properties"]["body"] = {"type": "object", "$ref": f"#/components/schemas/{op.request.body_type}"}
                required.append("body")
                
            if required:
                input_schema["required"] = required
                
            tools.append({
                "name": op.name,
                "description": op.description or f"Execute {op.name}",
                "inputSchema": input_schema,
                "authRequired": True, 
                "sideEffect": "write" if op.method.upper() in ["POST", "PUT", "PATCH", "DELETE"] else "read",
            })
        manifest = {"version": "1.0.0", "tools": tools}
        return {f"{module.name}-mcp-tools.json": json.dumps(manifest, indent=2) + "\n"}

@register_generator("mcp-gateway-config")
class McpGatewayConfigGenerator:
    def generate(self, module: ModuleSpec) -> dict[str, str]:
        config = {"name": module.name, "proxy": {"enabled": True, "target": "http://localhost:3000"}}
        return {f"{module.name}-gateway.yaml": yaml.safe_dump(config, sort_keys=False)}

@register_generator("mcp-app-ui-manifest")
class McpAppUiManifestGenerator:
    def generate(self, module: ModuleSpec) -> dict[str, str]:
        manifest = {"name": module.name, "ui_elements": ["sidebar", "dashboard"]}
        return {f"{module.name}-ui.json": json.dumps(manifest, indent=2)}

@register_generator("agentify-bundle")
class AgentifyBundleGenerator:
    def generate(self, module: ModuleSpec) -> dict[str, str]:
        return {f"{module.name}-agentify.json": json.dumps({"bundle": module.name}, indent=2)}

@register_generator("llms-txt")
class LlmsTxtGenerator:
    def generate(self, module: ModuleSpec) -> dict[str, str]:
        lines = [f"# {module.name}", "", "## API Endpoints", ""]
        for op in module.operations:
            lines.append(f"- `[{op.method.upper()}] {op.path}`: {op.description}")
        return {"llms.txt": "\n".join(lines) + "\n"}

@register_generator("agents-md")
class AgentsMdGenerator:
    def generate(self, module: ModuleSpec) -> dict[str, str]:
        lines = [f"# {module.name} Agent Capabilities", ""]
        for op in module.operations:
            lines.append(f"### {op.name}")
            lines.append(f"{op.description}")
            lines.append("")
        return {"AGENTS.md": "\n".join(lines) + "\n"}

@register_generator("skill-md")
class SkillMdGenerator:
    def generate(self, module: ModuleSpec) -> dict[str, str]:
        return {f"{module.name}-sdk-metadata.json": json.dumps({"target": "skill-md", "implemented": False, "reason": "minimal stub"})}
