from __future__ import annotations
from utag_core.ir import ModuleSpec
from utag_core.registry import register_generator

@register_generator("python-sdk")
class PythonSdkGenerator:
    def generate(self, module: ModuleSpec) -> dict[str, str]:
        lines = ["# generated by utag — python sdk", ""]
        lines.append("import httpx")
        lines.append("from typing import Any")
        lines.append("")
        lines.append("class ApiClient:")
        lines.append("    def __init__(self, base_url: str = ''):")
        lines.append("        self.base_url = base_url")
        lines.append("        self.client = httpx.AsyncClient(base_url=base_url)")
        lines.append("")
        
        for op in module.operations:
            req_type = op.request.body_type or "Any"
            res_type = "Any"
            if op.responses:
                for r in op.responses:
                    if 200 <= r.status_code < 300 and r.body_type:
                        res_type = r.body_type
                        break
                        
            args = ["self"]
            for p in op.request.path_params:
                args.append(f"{p.name}: str")
            for q in op.request.query_params:
                args.append(f"{q.name}: str")
            if op.request.body_type:
                args.append(f"body: {req_type}")
            
            args_str = ", ".join(args)
            lines.append(f"    async def {op.name}({args_str}) -> {res_type}:")
            
            path = op.path
            # python format string replacement
            # replace {param} with {param} for f-strings
            lines.append(f'        url = f"{{self.base_url}}{path}"')
            
            params_dict = "{" + ", ".join(f'"{q.name}": {q.name}' for q in op.request.query_params) + "}"
            if op.request.query_params:
                lines.append(f"        params = {params_dict}")
            else:
                lines.append("        params = None")
                
            method = op.method.upper()
            req_kwargs = "params=params"
            if op.request.body_type:
                req_kwargs += ", json=body"
                
            lines.append(f'        response = await self.client.request("{method}", url, {req_kwargs})')
            lines.append("        response.raise_for_status()")
            lines.append("        return response.json()")
            lines.append("")
            
        return {f"{module.name}_sdk.py": "\n".join(lines)}

@register_generator("go-sdk")
class GoSdkGenerator:
    def generate(self, module: ModuleSpec) -> dict[str, str]:
        lines = ["// generated by utag — go sdk", "package sdk", ""]
        lines.append("import (")
        lines.append('    "bytes"')
        lines.append('    "encoding/json"')
        lines.append('    "fmt"')
        lines.append('    "net/http"')
        lines.append('    "net/url"')
        lines.append('    "io"')
        lines.append('    "strings"')
        lines.append(")")
        lines.append("")
        lines.append("type ApiClient struct {")
        lines.append("    BaseURL    string")
        lines.append("    HTTPClient *http.Client")
        lines.append("}")
        lines.append("")
        lines.append("func NewApiClient(baseURL string) *ApiClient {")
        lines.append("    return &ApiClient{")
        lines.append("        BaseURL: baseURL,")
        lines.append("        HTTPClient: &http.Client{},")
        lines.append("    }")
        lines.append("}")
        lines.append("")
        
        for op in module.operations:
            req_type = op.request.body_type or "interface{}"
            res_type = "interface{}"
            if op.responses:
                for r in op.responses:
                    if 200 <= r.status_code < 300 and r.body_type:
                        res_type = r.body_type
                        break
                        
            args = []
            for p in op.request.path_params:
                args.append(f"{p.name} string")
            for q in op.request.query_params:
                args.append(f"{q.name} string")
            if op.request.body_type:
                args.append(f"body {req_type}")
            
            args_str = ", ".join(args)
            lines.append(f"func (c *ApiClient) {op.name.capitalize()}({args_str}) ({res_type}, error) {{")
            
            # Path parsing
            path = op.path
            for p in op.request.path_params:
                # very simplified replace
                path = path.replace(f"{{{p.name}}}", f"%s")
                
            path_args = ", ".join(p.name for p in op.request.path_params)
            if path_args:
                lines.append(f'    reqURL := c.BaseURL + fmt.Sprintf("{path}", {path_args})')
            else:
                lines.append(f'    reqURL := c.BaseURL + "{path}"')
            
            if op.request.query_params:
                lines.append("    parsedURL, err := url.Parse(reqURL)")
                lines.append("    if err != nil { return nil, err }")
                lines.append("    q := parsedURL.Query()")
                for q in op.request.query_params:
                    lines.append(f'    q.Add("{q.name}", {q.name})')
                lines.append("    parsedURL.RawQuery = q.Encode()")
                lines.append("    reqURL = parsedURL.String()")
                
            method = op.method.upper()
            if op.request.body_type:
                lines.append("    bodyBytes, err := json.Marshal(body)")
                lines.append("    if err != nil { return nil, err }")
                lines.append(f'    req, err := http.NewRequest("{method}", reqURL, bytes.NewBuffer(bodyBytes))')
                lines.append('    req.Header.Set("Content-Type", "application/json")')
            else:
                lines.append(f'    req, err := http.NewRequest("{method}", reqURL, nil)')
                
            lines.append("    if err != nil { return nil, err }")
            lines.append("    res, err := c.HTTPClient.Do(req)")
            lines.append("    if err != nil { return nil, err }")
            lines.append("    defer res.Body.Close()")
            lines.append("    if res.StatusCode >= 300 {")
            lines.append('        return nil, fmt.Errorf("HTTP %d", res.StatusCode)')
            lines.append("    }")
            lines.append(f"    var result {res_type}")
            lines.append("    if err := json.NewDecoder(res.Body).Decode(&result); err != nil { return nil, err }")
            lines.append("    return result, nil")
            lines.append("}")
            lines.append("")
            
        return {f"{module.name}_sdk.go": "\n".join(lines)}

@register_generator("java-sdk")
class JavaSdkGenerator:
    def generate(self, module: ModuleSpec) -> dict[str, str]:
        metadata = {"target": "java-sdk", "implemented": False, "reason": "compiler gate pending"}
        fixtures = {"sample": "example_data"}
        plan = f"# Validation Plan for {module.name} Java SDK\n\n1. Verify Maven dependency resolution.\n2. Run generated unit tests."
        return {
            f"{module.name}-sdk-metadata.json": json.dumps(metadata),
            f"{module.name}-sdk-fixtures.json": json.dumps(fixtures),
            f"{module.name}-validation-plan.md": plan
        }


@register_generator("kotlin-sdk")
class KotlinSdkGenerator:
    def generate(self, module: ModuleSpec) -> dict[str, str]:
        metadata = {"target": "kotlin-sdk", "implemented": False, "reason": "compiler gate pending"}
        fixtures = {"sample": "example_data"}
        plan = f"# Validation Plan for {module.name} Kotlin SDK\n\n1. Verify Gradle dependency resolution.\n2. Run generated unit tests."
        return {
            f"{module.name}-sdk-metadata.json": json.dumps(metadata),
            f"{module.name}-sdk-fixtures.json": json.dumps(fixtures),
            f"{module.name}-validation-plan.md": plan
        }


@register_generator("csharp-sdk")
class CSharpSdkGenerator:
    def generate(self, module: ModuleSpec) -> dict[str, str]:
        metadata = {"target": "csharp-sdk", "implemented": False, "reason": "compiler gate pending"}
        fixtures = {"sample": "example_data"}
        plan = f"# Validation Plan for {module.name} C# SDK\n\n1. Verify NuGet dependency resolution.\n2. Run generated unit tests."
        return {
            f"{module.name}-sdk-metadata.json": json.dumps(metadata),
            f"{module.name}-sdk-fixtures.json": json.dumps(fixtures),
            f"{module.name}-validation-plan.md": plan
        }


@register_generator("php-sdk")
class PhpSdkGenerator:
    def generate(self, module: ModuleSpec) -> dict[str, str]:
        metadata = {"target": "php-sdk", "implemented": False, "reason": "compiler gate pending"}
        fixtures = {"sample": "example_data"}
        plan = f"# Validation Plan for {module.name} PHP SDK\n\n1. Verify Composer dependency resolution.\n2. Run generated unit tests."
        return {
            f"{module.name}-sdk-metadata.json": json.dumps(metadata),
            f"{module.name}-sdk-fixtures.json": json.dumps(fixtures),
            f"{module.name}-validation-plan.md": plan
        }


@register_generator("ruby-sdk")
class RubySdkGenerator:
    def generate(self, module: ModuleSpec) -> dict[str, str]:
        metadata = {"target": "ruby-sdk", "implemented": False, "reason": "compiler gate pending"}
        fixtures = {"sample": "example_data"}
        plan = f"# Validation Plan for {module.name} Ruby SDK\n\n1. Verify Gemfile dependency resolution.\n2. Run generated unit tests."
        return {
            f"{module.name}-sdk-metadata.json": json.dumps(metadata),
            f"{module.name}-sdk-fixtures.json": json.dumps(fixtures),
            f"{module.name}-validation-plan.md": plan
        }


@register_generator("swift-sdk")
class SwiftSdkGenerator:
    def generate(self, module: ModuleSpec) -> dict[str, str]:
        metadata = {"target": "swift-sdk", "implemented": False, "reason": "compiler gate pending"}
        fixtures = {"sample": "example_data"}
        plan = f"# Validation Plan for {module.name} Swift SDK\n\n1. Verify Swift Package Manager dependency resolution.\n2. Run generated unit tests."
        return {
            f"{module.name}-sdk-metadata.json": json.dumps(metadata),
            f"{module.name}-sdk-fixtures.json": json.dumps(fixtures),
            f"{module.name}-validation-plan.md": plan
        }


@register_generator("rust-sdk")
class RustSdkGenerator:
    def generate(self, module: ModuleSpec) -> dict[str, str]:
        metadata = {"target": "rust-sdk", "implemented": False, "reason": "compiler gate pending"}
        fixtures = {"sample": "example_data"}
        plan = f"# Validation Plan for {module.name} Rust SDK\n\n1. Verify Cargo dependency resolution.\n2. Run generated unit tests."
        return {
            f"{module.name}-sdk-metadata.json": json.dumps(metadata),
            f"{module.name}-sdk-fixtures.json": json.dumps(fixtures),
            f"{module.name}-validation-plan.md": plan
        }
