from __future__ import annotations
import json

from utag_core.ir import ModuleSpec
from utag_core.registry import register_generator


@register_generator("mock-server")
class MockServerGenerator:
    def generate(self, module: ModuleSpec) -> dict[str, str]:
        lines = ["// generated by utag — mock server"]
        lines.append('const express = require("express");')
        lines.append('const app = express();')
        lines.append('app.use(express.json());')
        lines.append("")
        
        for op in module.operations:
            method = op.method.lower()
            express_path = op.path
            for p in op.request.path_params:
                express_path = express_path.replace(f"{{{p.name}}}", f":{p.name}")
                
            lines.append(f"app.{method}('{express_path}', (req, res) => {{")
            lines.append("  // Mock implementation")
            expected_status = 200
            if op.responses:
                expected_status = op.responses[0].status_code
                
            lines.append(f"  res.status({expected_status}).json({{}});")
            lines.append("});")
            lines.append("")
            
        lines.append("const PORT = process.env.PORT || 3000;")
        lines.append("app.listen(PORT, () => {")
        lines.append(f"  console.log('{module.name} mock server listening on port ' + PORT);")
        lines.append("});")
        
        return {f"{module.name}-mock.js": "\n".join(lines) + "\n"}

@register_generator("wiremock-stubs")
class WiremockStubsGenerator:
    def generate(self, module: ModuleSpec) -> dict[str, str]:
        import json
        mappings = []
        for op in module.operations:
            url_path = op.path
            # Replace OpenAPI {param} with Wiremock matching or exact values
            # Wiremock prefers URL Path matching
            for p in op.request.path_params:
                url_path = url_path.replace(f"{{{p.name}}}", f"test_{p.name}")
                
            request = {
                "method": op.method.upper(),
                "urlPath": url_path
            }
            
            if op.request.query_params:
                request["queryParameters"] = {
                    q.name: {"equalTo": f"test_{q.name}"} for q in op.request.query_params
                }
                
            expected_status = 200
            if op.responses:
                expected_status = op.responses[0].status_code
                
            response = {
                "status": expected_status,
            }
            if op.responses and op.responses[0].body_type:
                response["headers"] = {"Content-Type": "application/json"}
                response["jsonBody"] = {}
                
            mappings.append({
                "request": request,
                "response": response
            })
            
        out = {"mappings": mappings}
        return {f"{module.name}-wiremock.json": json.dumps(out, indent=2) + "\n"}

@register_generator("prism-config")
class PrismConfigGenerator:
    def generate(self, module: ModuleSpec) -> dict[str, str]:
        # Prism doesn't strictly need a config file, but if generated, it points to the spec.
        content = f"mock:\n  dynamic: false\n  host: 127.0.0.1\n  port: 4010\nspec: ./{module.name}.openapi.json\n"
        return {f"{module.name}-prism.yaml": content}
@register_generator("schemathesis-suite")
class SchemathesisSuiteGenerator:
    def generate(self, module: ModuleSpec) -> dict[str, str]:
        lines = ["# generated by utag — schemathesis suite", "import schemathesis", ""]
        lines.append(f'schema = schemathesis.from_path("{module.name}.openapi.json")')
        lines.append("")
        lines.append("@schema.parametrize()")
        lines.append("def test_api(case):")
        lines.append("    case.call_and_validate()")
        return {f"{module.name}-schemathesis.py": "\n".join(lines) + "\n"}

@register_generator("hurl-tests")
class HurlTestsGenerator:
    def generate(self, module: ModuleSpec) -> dict[str, str]:
        lines = ["# generated by utag — hurl tests"]
        for op in module.operations:
            lines.append("")
            # Build URL
            url = op.path
            for p in op.request.path_params:
                url = url.replace(f"{{{p.name}}}", f"test_{p.name}")
            
            if op.request.query_params:
                qs = "&".join(f"{q.name}=test_{q.name}" for q in op.request.query_params)
                url = f"{url}?{qs}"
                
            lines.append(f"{op.method.upper()} {{{{BASE_URL}}}}{url}")
            
            if op.request.body_type:
                lines.append("Content-Type: application/json")
                lines.append("```json")
                lines.append("{}")
                lines.append("```")
                
            expected_status = 200
            if op.responses:
                expected_status = op.responses[0].status_code
                
            lines.append(f"HTTP {expected_status}")
            if op.responses and op.responses[0].body_type:
                lines.append("[Asserts]")
                lines.append("header \"Content-Type\" == \"application/json\"")
                
        return {f"{module.name}.hurl": "\n".join(lines) + "\n"}

@register_generator("postman-collection")
class PostmanCollectionGenerator:
    def generate(self, module: ModuleSpec) -> dict[str, str]:
        import json
        collection = {
            "info": {
                "name": module.name,
                "description": module.description,
                "schema": "https://schema.getpostman.com/json/collection/v2.1.0/collection.json"
            },
            "item": []
        }
        
        for op in module.operations:
            # Build path variables
            path_vars = []
            postman_path = op.path
            for p in op.request.path_params:
                postman_path = postman_path.replace(f"{{{p.name}}}", f":{p.name}")
                path_vars.append({
                    "key": p.name,
                    "value": f"<{p.name}>"
                })
                
            # Build query parameters
            query_params = []
            for q in op.request.query_params:
                query_params.append({
                    "key": q.name,
                    "value": f"<{q.name}>"
                })
                
            # Build request body
            body = None
            if op.request.body_type:
                body = {
                    "mode": "raw",
                    "raw": "{}"
                }
                
            item = {
                "name": op.name,
                "request": {
                    "method": op.method.upper(),
                    "header": [{"key": "Content-Type", "value": "application/json"}] if op.request.body_type else [],
                    "url": {
                        "raw": f"{{{{baseUrl}}}}{postman_path}",
                        "host": ["{{baseUrl}}"],
                        "path": [p for p in postman_path.split("/") if p],
                        "query": query_params,
                        "variable": path_vars
                    }
                }
            }
            if body:
                item["request"]["body"] = body
                
            collection["item"].append(item)
            
        return {f"{module.name}-postman.json": json.dumps(collection, indent=2)}


@register_generator("contract-test-suite")
class ContractTestSuiteGenerator:
    def generate(self, module: ModuleSpec) -> dict[str, str]:
        lines = ["// generated by utag — contract test suite", ""]
        lines.append('import { ApiClient } from "./' + module.name.replace('_', '-') + '-client";')
        lines.append('import { describe, expect, test } from "@jest/globals";')
        lines.append("")
        lines.append("describe('API Contract Tests', () => {")
        lines.append("  const client = new ApiClient();")
        lines.append("")
        
        for op in module.operations:
            lines.append(f"  test('should execute {op.name} successfully', async () => {{")
            # Build dummy args
            args = []
            for p in op.request.path_params: args.append('"test"')
            for q in op.request.query_params: args.append('"test"')
            if op.request.body_type: args.append("{}")
            
            lines.append(f"    const result = await client.{op.name}({', '.join(args)});")
            lines.append("    expect(result).toBeDefined();")
            lines.append("  });")
            lines.append("")
            
        lines.append("});")
        return {f"{module.name}-contract-tests.ts": "\n".join(lines) + "\n"}

@register_generator("behavior-verification-manifest")
class BehaviorVerificationManifestGenerator:
    def generate(self, module: ModuleSpec) -> dict[str, str]:
        import yaml
        manifest = {
            "verification_target": module.name,
            "required_behaviors": [
                {
                    "operation": op.name,
                    "method": op.method.upper(),
                    "path": op.path
                } for op in module.operations
            ]
        }
        return {f"{module.name}-behavior.yaml": yaml.safe_dump(manifest, sort_keys=False)}
