from __future__ import annotations

from utag_core.ir import ModuleSpec
from utag_core.registry import register_generator
@register_generator("typescript-types")
class TypeScriptTypesGenerator:
    def generate(self, module: ModuleSpec) -> dict[str, str]:
        lines = ["// generated by utag — typescript types", ""]
        
        ts_map = {
            "string": "string",
            "integer": "number",
            "number": "number",
            "boolean": "boolean",
            "datetime": "Date",
            "any": "any"
        }
        
        for t in module.types:
            if t.description:
                lines.append(f"/** {t.description} */")
            lines.append(f"export interface {t.name} {{")
            for f in t.fields:
                # Determine base type
                base = ts_map.get(f.type.value if hasattr(f.type, "value") else str(f.type), str(f.type))
                if f.array:
                    base = f"Array<{base}>"
                if f.nullable:
                    base = f"{base} | null"
                    
                opt = "?" if not f.required else ""
                
                if f.description:
                    lines.append(f"  /** {f.description} */")
                lines.append(f"  {f.name}{opt}: {base};")
            lines.append("}")
            lines.append("")
            
        return {f"{module.name.replace('_', '-')}-types.ts": "\n".join(lines)}

@register_generator("fetch-client")
class FetchClientGenerator:
    def generate(self, module: ModuleSpec) -> dict[str, str]:
        lines = ["// generated by utag — fetch client", ""]
        lines.append(f'import type {{ {", ".join(t.name for t in module.types)} }} from "./{module.name.replace("_", "-")}-types";')
        lines.append("")
        lines.append("export class ApiClient {")
        lines.append("  constructor(private baseUrl: string = '') {}")
        lines.append("")
        
        for op in module.operations:
            req_type = op.request.body_type or "any"
            res_type = "any"
            if op.responses:
                for r in op.responses:
                    if 200 <= r.status_code < 300 and r.body_type:
                        res_type = r.body_type
                        break
                        
            args = []
            for p in op.request.path_params:
                args.append(f"{p.name}: string")
            for q in op.request.query_params:
                args.append(f"{q.name}: string")
            if op.request.body_type:
                args.append(f"body: {req_type}")
            
            args_str = ", ".join(args)
            lines.append(f"  async {op.name}({args_str}): Promise<{res_type}> {{")
            
            # Path parameter replacement
            path = op.path
            for p in op.request.path_params:
                path = path.replace(f"{{{p.name}}}", f"${{{p.name}}}")
            
            # Query parameters
            if op.request.query_params:
                q_params = ", ".join(f"{q.name}" for q in op.request.query_params)
                lines.append(f"    const qs = new URLSearchParams({{ {q_params} }}).toString();")
                lines.append(f"    const url = `${{this.baseUrl}}{path}?${{qs}}`;")
            else:
                lines.append(f"    const url = `${{this.baseUrl}}{path}`;")
                
            fetch_args = [f'method: "{op.method.upper()}"']
            if op.request.body_type:
                fetch_args.append("headers: { 'Content-Type': 'application/json' }")
                fetch_args.append("body: JSON.stringify(body)")
                
            lines.append(f"    const res = await fetch(url, {{ {', '.join(fetch_args)} }});")
            lines.append("    if (!res.ok) throw new Error(res.statusText);")
            lines.append("    return res.json();")
            lines.append("  }")
            lines.append("")
            
        lines.append("}")
        return {f"{module.name.replace('_', '-')}-client.ts": "\n".join(lines)}

@register_generator("tanstack-query-hooks")
class TanstackQueryHooksGenerator:
    def generate(self, module: ModuleSpec) -> dict[str, str]:
        lines = ["// generated by utag — tanstack query hooks", ""]
        lines.append('import { useQuery, useMutation } from "@tanstack/react-query";')
        lines.append(f'import {{ ApiClient }} from "./{module.name.replace("_", "-")}-client";')
        lines.append(f'import type {{ {", ".join(t.name for t in module.types)} }} from "./{module.name.replace("_", "-")}-types";')
        lines.append("")
        lines.append("const client = new ApiClient();")
        lines.append("")
        
        for op in module.operations:
            is_query = op.method.upper() == "GET"
            res_type = "any"
            if op.responses:
                for r in op.responses:
                    if 200 <= r.status_code < 300 and r.body_type:
                        res_type = r.body_type
                        break
            
            # For mutations, we need to pass a single object or we can just pass the args.
            if is_query:
                args = []
                for p in op.request.path_params: args.append(f"{p.name}: string")
                for q in op.request.query_params: args.append(f"{q.name}: string")
                args_str = ", ".join(args)
                lines.append(f"export const use{op.name[0].upper() + op.name[1:]} = ({args_str}) => {{")
                call_args = ", ".join(p.name for p in op.request.path_params + op.request.query_params)
                
                query_key = f"['{op.name}', {call_args}]" if call_args else f"['{op.name}']"
                
                lines.append(f"export const use{op.name.capitalize()} = ({args_str}) => {{")
                lines.append(f"  return useQuery<{res_type}, Error>({{")
                lines.append(f"    queryKey: {query_key},")
                lines.append(f"    queryFn: () => client.{op.name}({call_args}),")
                lines.append("  });")
                lines.append("};")
            else:
                req_type = op.request.body_type or "any"
                args = []
                for p in op.request.path_params: args.append(f"{p.name}: string")
                for q in op.request.query_params: args.append(f"{q.name}: string")
                if op.request.body_type:
                    args.append(f"body: {req_type}")
                args_str = ", ".join(args)
                lines.append(f"export const use{op.name[0].upper() + op.name[1:]} = () => {{")
                call_args = ", ".join(x for x in [p.name for p in op.request.path_params + op.request.query_params] + (["body"] if op.request.body_type else []))
                
                lines.append(f"export const use{op.name.capitalize()} = () => {{")
                lines.append(f"  return useMutation<{res_type}, Error, {{ {args_str} }}>({{")
                lines.append(f"    mutationFn: (vars) => client.{op.name}({', '.join(f'vars.{x}' for x in [p.name for p in op.request.path_params + op.request.query_params] + (['body'] if op.request.body_type else []))}),")
                lines.append("  });")
                lines.append("};")
            lines.append("")
            
        return {f"{module.name.replace('_', '-')}-hooks.ts": "\n".join(lines)}

@register_generator("msw-handlers")
class MswHandlersGenerator:
    def generate(self, module: ModuleSpec) -> dict[str, str]:
        lines = ["// generated by utag — msw handlers", ""]
        lines.append('import { http, HttpResponse } from "msw";')
        lines.append(f'import type {{ {", ".join(t.name for t in module.types)} }} from "./{module.name.replace("_", "-")}-types";')
        lines.append("")
        lines.append(f"export const {module.name}Handlers = [")
        
        for op in module.operations:
            method = op.method.lower()
            path = op.path
            # Replace {param} with :param for MSW/Express syntax
            for p in op.request.path_params:
                path = path.replace(f"{{{p.name}}}", f":{p.name}")
            
            lines.append(f"  http.{method}('*{path}', ({{ params, request }}) => {{")
            lines.append("    // TODO: implement mock response logic")
            lines.append("    return HttpResponse.json({});")
            lines.append("  }),")
            
        lines.append("];")
        return {f"{module.name.replace('_', '-')}-msw.ts": "\n".join(lines)}

# Stubs for the rest
@register_generator("typescript-sdk")
class TypeScriptSdkGenerator:
    def generate(self, module: ModuleSpec) -> dict[str, str]:
        return {f"{module.name}-sdk.ts": "// sdk stub\n"}

@register_generator("swr-hooks")
class SwrHooksGenerator:
    def generate(self, module: ModuleSpec) -> dict[str, str]:
        return {f"{module.name}-swr.ts": "// swr stub\n"}

@register_generator("zustand-client")
class ZustandClientGenerator:
    def generate(self, module: ModuleSpec) -> dict[str, str]:
        return {f"{module.name}-zustand.ts": "// zustand stub\n"}

@register_generator("nock-tests")
class NockTestsGenerator:
    def generate(self, module: ModuleSpec) -> dict[str, str]:
        return {f"{module.name}-nock.ts": "// nock stub\n"}

@register_generator("supertest-tests")
class SupertestTestsGenerator:
    def generate(self, module: ModuleSpec) -> dict[str, str]:
        return {f"{module.name}-supertest.ts": "// supertest stub\n"}

@register_generator("orpc-router")
class OrpcRouterGenerator:
    def generate(self, module: ModuleSpec) -> dict[str, str]:
        return {f"{module.name}-orpc.ts": "// orpc stub\n"}

@register_generator("axios-client")
class AxiosClientGenerator:
    def generate(self, module: ModuleSpec) -> dict[str, str]:
        return {f"{module.name}-axios.ts": "// axios stub\n"}
