"""IR -> Zod v4 TypeScript schema text artifact (validated via tsc when Node present)."""
from __future__ import annotations

from utag_core.ir import ModuleSpec
from utag_core.registry import register_generator
from utag_generators._codegen import zod_chain


@register_generator("zod-schemas")
class ZodGenerator:
    def generate(self, module: ModuleSpec) -> dict[str, str]:
        lines = ["// generated by utag 2.0.0 — deterministic; do not edit by hand",
                 'import { z } from "zod/v4";', ""]
        for t in module.types:
            lines.append(f"export const {t.name}Schema = z.strictObject({{")
            for f in t.fields:
                lines.append(f"  {f.name}: {zod_chain(f)},")
            lines.append("});")
            lines.append(f"export type {t.name} = z.infer<typeof {t.name}Schema>;")
            lines.append("")
        return {f"{module.name.replace('_', '-')}.ts": "\n".join(lines).rstrip() + "\n"}
