#!/usr/bin/env python3
"""sources:sync — write sources.lock.toml from REAL resolved data only.

PyPI deps: version + license via importlib.metadata (what's actually installed).
Upstream repos: commit SHA resolved live from the GitHub API; on network failure
the field is written as "UNRESOLVED" — never fabricated (spec: fail clearly).
"""
from __future__ import annotations

import importlib.metadata as md
import json
import urllib.request

PYPI = ["pydantic", "pydantic-settings", "PyYAML", "jsonschema",
        "openapi-spec-validator", "instructor", "pydantic-ai-slim", "pytest"]
REPOS = {
    "pydantic": "pydantic/pydantic",
    "instructor": "567-labs/instructor",
    "pydantic-ai": "pydantic/pydantic-ai",
    "pi": "earendil-works/pi",
    "design-md": "google-labs-code/design.md",
    "openapi": "OAI/OpenAPI-Specification",
    "cobra": "spf13/cobra",
    "cobra-cli": "spf13/cobra-cli",
    "viper": "spf13/viper",
    "mapstructure": "go-viper/mapstructure",
    "twelve-factor": "twelve-factor/twelve-factor",
}


def head_sha(repo: str) -> str:
    """git ls-remote first (no API rate limit), GitHub API as fallback."""
    import subprocess
    try:
        out = subprocess.run(["git", "ls-remote", f"https://github.com/{repo}", "HEAD"],
                             capture_output=True, text=True, timeout=20)
        if out.returncode == 0 and out.stdout.strip():
            return out.stdout.split()[0]
    except Exception:
        pass
    try:
        req = urllib.request.Request(
            f"https://api.github.com/repos/{repo}/commits/HEAD",
            headers={"Accept": "application/vnd.github+json", "User-Agent": "utag/2.0.0"})
        with urllib.request.urlopen(req, timeout=15) as r:
            return json.load(r)["sha"]
    except Exception:
        return "UNRESOLVED"


def main() -> None:
    lines = ["# sources.lock.toml — generated by scripts/sources.py; real data only\n"]
    lines.append("[pypi]")
    for p in PYPI:
        try:
            meta = md.metadata(p)
            lic = (meta.get("License-Expression") or meta.get("License") or "see-classifiers").split("\n")[0][:60]
            lines.append(f'{p.replace("-", "_")} = {{ version = "{md.version(p)}", license = "{lic}" }}')
        except md.PackageNotFoundError:
            lines.append(f'{p.replace("-", "_")} = {{ version = "NOT-INSTALLED" }}')
    lines.append("\n[upstream]")
    for name, repo in REPOS.items():
        lines.append(f'{name.replace("-", "_")} = {{ repo = "https://github.com/{repo}", commit = "{head_sha(repo)}" }}')
    open("sources.lock.toml", "w").write("\n".join(lines) + "\n")
    print(open("sources.lock.toml").read())


if __name__ == "__main__":
    main()
