package github

import (
	"encoding/json"
	"fmt"
	"strings"

	"utag/control-plane/internal/store"
)

// BuildPRBody: artifact table + each ValidationReport in a collapsible block.
// The reports ARE the review evidence — this is what makes agent PRs reviewable.
func BuildPRBody(job *store.Job, artifacts []store.Artifact) string {
	var b strings.Builder
	fmt.Fprintf(&b, "## utag generation report\n\n")
	fmt.Fprintf(&b, "| | |\n|---|---|\n| job | `%s` |\n| target | `%s` |\n| input | `%s` |\n| status | **%s** |\n\n",
		job.ID, job.Target, job.InputKind, job.Status)
	fmt.Fprintf(&b, "### Artifacts (%d)\n\n", len(artifacts))
	for _, a := range artifacts {
		valid := "—"
		if a.Report != "" {
			var r struct {
				Valid       bool   `json:"valid"`
				ValidatorID string `json:"validator_id"`
			}
			if json.Unmarshal([]byte(a.Report), &r) == nil {
				if r.Valid {
					valid = "✅ " + r.ValidatorID
				} else {
					valid = "❌ " + r.ValidatorID
				}
			}
		}
		fmt.Fprintf(&b, "<details><summary><code>%s</code> — %s</summary>\n\n", a.Path, valid)
		if a.Report != "" {
			fmt.Fprintf(&b, "```json\n%s\n```\n", a.Report)
		}
		fmt.Fprintf(&b, "</details>\n\n")
	}
	b.WriteString("---\n_Generated by utag control-plane. Deterministic; reports are the review._\n")
	return b.String()
}

// Deliverer turns a completed job with GitHub metadata into a pull request.
type Deliverer struct{ Client *Client }

func (d *Deliverer) Deliver(job *store.Job, artifacts []store.Artifact) (string, error) {
	var meta JobMeta
	if err := json.Unmarshal([]byte(job.Metadata), &meta); err != nil || meta.Repo == "" {
		return "", fmt.Errorf("no github metadata: %v", err)
	}
	token, err := d.Client.InstallationToken(meta.InstallationID)
	if err != nil {
		return "", err
	}
	branch := "utag/job-" + job.ID[:8]
	title := fmt.Sprintf("utag: %s from %s", job.Target, meta.SourcePath)
	var prArts []prArtifact
	for _, a := range artifacts {
		prArts = append(prArts, prArtifact{Path: "utag/" + job.Target + "/" + a.Path, Content: a.Content})
	}
	url, err := d.Client.CreateArtifactPR(token, meta.Repo, meta.BaseBranch, branch,
		title, BuildPRBody(job, artifacts), prArts)
	if err != nil {
		return "", err
	}
	if meta.IssueNumber > 0 {
		_ = d.Client.Comment(token, meta.Repo, meta.IssueNumber,
			fmt.Sprintf("utag: opened %s (job `%s`)", url, job.ID))
	}
	return url, nil
}
