import utag_generators
import json
from utag_core.registry import get_generator
from utag_core.ir import ModuleSpec

def test_udc_component_generator():
    gen = get_generator("udc-component")
    
    # Create mock provenance data for UDC
    udc_json = {
        "info": {"title": "TestUDC", "version": "1.0.0"},
        "domains": {
            "components": {
                "Button": {
                    "version": "1.0.0",
                    "spec": {"props": {"label": "string"}}
                }
            }
        }
    }
    
    module = ModuleSpec(
        name="testmod",
        provenance={"udc_json": json.dumps(udc_json)}
    )
    
    out = gen.generate(module)
    assert "Button.tsx" in out
    content = out["Button.tsx"]
    assert "// generated by utag udc-component" in content
    assert "export function Button" in content
    assert "label" in content
