name: Go CI

on:
  push:
    branches: [ "main" ]
    paths:
      - 'control-plane/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'control-plane/**'

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: control-plane
    steps:
    - uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'
    - name: Run tests
      run: go test -v ./...
